package sandbox

import (
	"testing"

	"github.com/carapace-sh/carapace"
	"github.com/carapace-sh/carapace/internal/mock"
	"github.com/spf13/cobra"
)

type Sandbox struct {
	t    *testing.T
	cmdF func() *cobra.Command
	env  map[string]string
	keep bool
	mock *mock.Mock
}

func newSandbox(t *testing.T, f func() *cobra.Command) Sandbox {
	_ = "STUB: not implemented"
	return *new(Sandbox)
}

// Keep prevents removal of the sandbox directory.
func (s *Sandbox) Keep() { _ = "STUB: not implemented"; return }

func (s *Sandbox) Env(key, value string) { _ = "STUB: not implemented"; return }

func (s *Sandbox) remove() { _ = "STUB: not implemented"; return }

func (s *Sandbox) ClearCache() { _ = "STUB: not implemented"; return }

// Files creates files within the sandbox directory.
//
//	s.Files(
//		"file1.txt", "content of file1.txt",
//		"dir1/file2.md", "content of file2.md",
//	)
func (s *Sandbox) Files(args ...string) { _ = "STUB: not implemented"; return }

// Reply mocks a command for given arguments (Only works for `(Context).Command`).
func (s *Sandbox) Reply(args ...string) reply { _ = "STUB: not implemented"; return *new(reply) }

type reply struct {
	*Sandbox
	call string
}

// With sets the output for the mocked command.
func (r reply) With(s string) { _ = "STUB: not implemented"; return }

// NewContext creates a new context enriched with sandbox specifics.
func (s *Sandbox) NewContext(args ...string) carapace.Context {
	_ = "STUB: not implemented"
	return *new(carapace.Context)
}

// TODO set mockedreplies in context

// Run executes the sandbox with given arguments.
func (s *Sandbox) Run(args ...string) run { _ = "STUB: not implemented"; return *new(run) }

type run struct {
	t       *testing.T
	id      string
	dir     string
	context carapace.Context
	actual  carapace.Action
}

// TODO rename
func (r run) invoke(a carapace.Action) string { _ = "STUB: not implemented"; return "" }

// Expects validates output of Run with given Action.
func (r run) Expect(expected carapace.Action) { _ = "STUB: not implemented"; return }

// t.Parallel() TODO prevent concurrent map write for this (storage.go)

func (r run) ExpectNot(unexpected carapace.Action) { _ = "STUB: not implemented"; return }

// t.Parallel() TODO prevent concurrent map write for this (storage.go)

// TODO yuck - print the action?

func (r run) Output() carapace.Action {
	_ = "STUB: not implemented"

	// Command executes the command generated by given function.
	return *new(carapace.Action)
}

func Command(t *testing.T, cmdF func() *cobra.Command) (f func(func(s *Sandbox))) {
	_ = "STUB: not implemented"
	return nil
}

// Package invokes `go run` on given package.
func Package(t *testing.T, pkg string) (f func(func(s *Sandbox))) {
	_ = "STUB: not implemented"
	return nil
}

// `go run` needs to run in actual workdir and not the sandbox dir

// Action executes a a command with the action return by given function as PositionalAny.
func Action(t *testing.T, actionF func() carapace.Action) (f func(func(s *Sandbox))) {
	_ = "STUB: not implemented"
	return nil
}
